### ISSUE TITLE
Generate a scss file but import in the component a css file

### ISSUE THREAD

**Issue by BrunoAlencar** [dbaikov/vscode-angular2-component-generator#5]
Generate a scss file but import in the component a css file.

![report sass](https://cloud.githubusercontent.com/assets/11480376/26286590/91c8efae-3e3f-11e7-9a16-cda479147dae.png)

**Comment by dbaikov** [comment]
Hey Bruno,

Thanks for catching it! I fixed it and pushed new version to vscode marketplace.
Just update the extension. If it doesn't prompt you for the update - run `ext install vscode-angular2-component-generator` from vscode.

**Comment by BrunoAlencar** [comment]
Thanks Dmytro for fast answer and for this awesome extension!
